###########################
# CityBuild System 1.19.4 #
#    Coded by XenoDEV     #
###########################

automessages:
  - Ich spiele Minecraft
  - Hier macht Zocken spaß

### Resettimer in Sekunden
resettime: 604800